Schools/Models/Section.cs
namespace Schools.Models
{
    public class Section
    {
        public int SectionId { get; set; }
        public string SectionName { get; set; }
    }
}

Schools/Models/Subjects.cs
namespace Schools.Models
{
    public class Subjects
    {
        public int SubjectsId { get; set; }
        public int ClassId { get; set; }
        public Class Class { get; set; }
        public string SubjectsName { get; set; }
    }
}

Schools/Controllers/ClassController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Configuration;
using System.Data;
using Schools.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using NuGet.Protocol.Plugins;
using System.Data.Common;

namespace Schools.Controllers
{
    public class ClassController : Controller
    {
        public IConfiguration Configuration { get; }
        public ClassController(IConfiguration configuration)
        {
            Configuration = configuration;
           
        }
        public IActionResult Index()
        {
            List<Class> grade = new List<Class>();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_GetClass", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataReader dr = cmd.ExecuteReader();
                    DataTable dt = new DataTable();
                    dt.Load(dr);
                    foreach(DataRow row in dt.Rows)
                    {
                        grade.Add(new Class
                        {
                            ClassId = Convert.ToInt32(row["ClassId"]),
                            ClassName = row["ClassName"].ToString()
                        });
                       
                    }    

                }
            }
            return View(grade);
        }
        public IActionResult CreateClass()
        {
            ViewBag.Section = GetSection();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateClass(Class grade)
        {
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using(SqlCommand cmd = new SqlCommand("sp_InsertClass", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@SectionId", grade.SectionId);
                    cmd.Parameters.AddWithValue("@ClassName", grade.ClassName);
                    cmd.ExecuteNonQuery();
                }
            }
                return RedirectToAction("Index");
        }

        public IActionResult EditClass(int? id)
        {
            Class classname=new Class();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_GetClass", con))
                {
                    cmd.CommandType=CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ClassId", id);

                    using (SqlDataReader dataReader =  cmd.ExecuteReader())
                    {
                        while (dataReader.Read())
                        {
                            classname.ClassId = Convert.ToInt32(dataReader["ClassId"]);
                            classname.SectionId = Convert.ToInt32(dataReader["ClassId"]);
                            classname.ClassName = Convert.ToString(dataReader["ClassName"]);
                            con.Close();
                        }
                    }
                }
            }
               
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditClass(Class grade, int? id)
        {
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_UpdateClass", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ClassId", id);
                    cmd.Parameters.AddWithValue("@SectionId", grade.SectionId);
                    cmd.Parameters.AddWithValue("@ClassName", grade.ClassName);
                    cmd.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteClass(int id)
        {
        using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
        {
            con.Open();
                
                using (SqlCommand cmd= new SqlCommand("sp_DeleteClass", con))
                {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ClassId", id);
                cmd.ExecuteNonQuery();
                con.Close();
                }
            }

            return RedirectToAction("Index");
        }

        private List<Section> GetSection()
        {
            var section = new List<Section>();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (var command = new SqlCommand("SELECT * FROM Section", con))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            section.Add(new Section
                            {
                                SectionId = Convert.ToInt32(reader["SectionId"]),
                                SectionName = reader["SectionName"].ToString()
                            });
                        }
                    }
                }
            }
            return section;
        }

        public IActionResult Section()
        {
            List<Section> section = new List<Section>();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_GetSection", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataReader dr = cmd.ExecuteReader();
                    DataTable dt = new DataTable();
                    dt.Load(dr);
                    foreach (DataRow row in dt.Rows)
                    {
                        section.Add(new Section
                        {
                            SectionId = Convert.ToInt32(row["SectionId"]),
                            SectionName = row["SectionName"].ToString()

                        });
                    }

                }
            }
            return View(section);
        }
        public IActionResult CreateSection()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSection(Section section)
        {
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_InsertSection", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    
                    cmd.Parameters.AddWithValue("@SectionName", section.SectionName);
                    cmd.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Section");
        }

        public IActionResult EditSection(int? id)
        {
           Section section = new Section();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_GetSectionId", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@SectionId", id);

                    using (SqlDataReader dataReader = cmd.ExecuteReader())
                    {
                        while (dataReader.Read())
                        {
                            section.SectionId = Convert.ToInt32(dataReader["SectionId"]);
                            section.SectionName = Convert.ToString(dataReader["SectionName"]);
                            
                        }
                    }
                    con.Close();
                }
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSection(Section section, int? id)
        {
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_UpdateSection", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@SectionId", id);
                    cmd.Parameters.AddWithValue("@SectionName", section.SectionName);
                    cmd.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Section");
        }

        [HttpPost]
        public IActionResult DeleteSection(int id)
        {
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand("sp_DeleteClass", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@SectionId", id);
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }

            return RedirectToAction("Section");

Schools/Views/Class/CreateClass.cshtml
@model Class
@{
    ViewData["Title"] = "CreateClass";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Account
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SectionId">Section</label>
                <select asp-for="SectionId" class="form-select" asp-items="@(new SelectList(ViewBag.Section,"SectionId","SectionName"))">
                    <option value="disabled selected">Section</option>
                </select>
                <span asp-validation-for="SectionId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ClassName">Class Name</label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
           
            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="Class asp-action="Index" class="btn btn-secondary" style="width:150px">
                  Back to Class
                </a>
            </div>
            
        </div>
    </div>

</form>

Schools/Views/Class/CreateSection.cshtml
@model Section
@{
    ViewData["Title"] = "CreateSection";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Section
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SectionName">Section</label>
                <input asp-for="SectionName" class="form-control" />
                <span asp-validation-for="SectionName" class="text-danger"></span>
            </div>

    <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="Class" asp-action="Section" class="btn btn-secondary" style="width:150px">
                    Back to Account
                </a>
    </div>
            
        </div>
    </div>

</form>

Schools/Views/Class/CreateSubjects.cshtml
@model Subjects
@{
    ViewData["Title"] = "CreateSubjects";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Subject
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SubjectsName">Subject</label>
                <input asp-for="SubjectsName" class="form-control" />
                <span asp-validation-for="SubjectsName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ClassId">Class</label>
                <select asp-for="ClassId" class="form-select" asp-items="@(new SelectList(ViewBag.Class,"ClassId","ClassName"))">
                    <option>Select Class</option>
                </select>
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="Class" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    Back to Subject
                </a>
            </div>
                       
        </div>
    </div>

</form>

Schools/Views/Class/EditClass.cshtml
@model Class
@{
    ViewData["Title"] = "EditClass";
}

<form method="post" asp-action="EditClass">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Account
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SectionId">Section</label>
                <select asp-for="SectionId" class="form-select" asp-items="@(new SelectList(ViewBag.Section,"SectionId","SectionName"))">
                    <option value="disabled selected">Section</option>
                </select>
                <span asp-validation-for="SectionId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ClassName">Class Name</label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="Class asp-action="Index" class="btn btn-secondary" style="width:150px">
                    Back to Class
                </a>
            </div>

        </div>
    </div>

</form>

Schools/Views/Class/EditSection.cshtml
@model Section
@{
    ViewData["Title"] = "EditSection";
}

<form method="post" asp-action="EditSection">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Section
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SectionName">Section</label>
                <input asp-for="SectionName" class="form-control" />
                <span asp-validation-for="SectionName" class="text-danger"></span>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Save Record</button>
                <a asp-controller="Class" asp-action="Section" class="btn btn-secondary" style="width:150px">
                    Back to Account
                </a>
            </div>

        </div>
    </div>

</form>

Schools/Views/Class/EditSubjects.cshtml
@model Subjects
@{
    ViewData["Title"] = "EditSubjects";
}

<form method="post" asp-action="EditSubjects">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Subject
            </h2>
            <hr />
            <div class="mb-3">
                <label asp-for="SubjectsName">Subject</label>
                <input asp-for="SubjectsName" class="form-control" />
                <span asp-validation-for="SubjectsName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ClassId">Class</label>
                <select asp-for="ClassId" class="form-select" asp-items="@(new SelectList(ViewBag.Class,"ClassId","ClassName"))">
                    <option>Select Class</option>
                </select>
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>



            <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            <a asp-controller="Class" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to Subject
            </a>
        </div>
    </div>

</form>

Schools/Views/Class/Index.cshtml
@model IEnumerable<Class>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Class</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Class" asp-action="CreateClass" class="btn btn-primary" style="width:250px">
                Create New Class
            </a>
        </div>
    </div>
</div>
<table class="table-bordered table-striped" style="width:100%">
    <thead>
        <tr>

            <th>Class</th>
            <th>Section</th>
            <th><label>Action</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>

                <td width="50">
                    @obj.ClassName
                </td>
                <td width="50">
                    @obj.Section
                </td>
                <td width="50">
                    <a asp-controller="Class" asp-action="EditAccountType" asp-route-id="@obj.ClassId" class="btn btn-success btn-mini"><i class="fas fa-edit"> Edit</i></a>
                    <a asp-controller="Class" asp-action="DeleteAccountType" asp-route-id="@obj.ClassId" class="btn btn-danger btn-mini"><i class="fas fa-trash-alt"> Delete</i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

Schools/Views/Class/Section.cshtml
@model IEnumerable<Section>
@{
    ViewData["Title"] = "Section";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Section</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Class" asp-action="CreateSection" class="btn btn-primary" style="width:250px">
                Create New Section
            </a>
        </div>
    </div>
</div>
<table class="table-bordered table-striped" style="width:100%">
    <thead>
        <tr>

            <th>Section</th>
            <th><label>Action</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>

                <td width="50">
                    @obj.SectionName
                </td>
                <td width="50">
                    <a asp-controller="Class" asp-action="EditSection" asp-route-id="@obj.SectionId" class="btn btn-success btn-mini"><i class="fas fa-edit"> Edit</i></a>
                    <a asp-controller="Class" asp-action="DeleteSection" asp-route-id="@obj.SectionId" class="btn btn-danger btn-mini"><i class="fas fa-trash-alt"> Delete</i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

Schools/Views/Class/Subjects.cshtml
@model IEnumerable<Subjects>
@{
    ViewData["Title"] = "Subjects";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Subjects</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Class" asp-action="CreateSubjects" class="btn btn-primary" style="width:250px">
                Create New Subject
            </a>
        </div>
    </div>
</div>
<table class="table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Subject Name</th>
            <th>Class</th>
            
            <th>
                <label>Action</label>
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var obj in Model)
        {
            <tr>
                <td width="100">
                    @obj.SubjectsName
                </td>
                <td width="50">
                    @obj.ClassId
                </td>
               
                <td width="50" class="justify-content-end">

                    <a asp-controller="Class" asp-action="EditSubjects" asp-route-id="@obj.SubjectsId" class="btn btn-success btn-mini"><i class="fas fa-edit"> Edit</i></a>
                    <a asp-controller="Class" asp-action="DeleteSubjects" asp-route-id="@obj.SubjectsId" class="btn btn-danger btn-mini"><i class="fas fa-trash-alt"> Delete</i></a>

                </td>
            </tr>
        }
    </tbody>
</table>