Schools/Models/School.cs
namespace Schools.Models
{
    public class School
    {
        public int SchoolsId { get; set; }
        public string SchoolsName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }

    }
}

Schools/Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System;
using System.Data;
using Schools.Models;
using Microsoft.Data.SqlClient;
using System.IO;
using NuGet.Packaging.Signing;


namespace Schools.Controllers
{
    public class SchoolController : Controller
    {
        
        public IConfiguration Configuration { get; }
        public IWebHostEnvironment Webhost { get; }
        public SchoolController (IConfiguration configuration, IWebHostEnvironment webHost)
        {
            Configuration = configuration;
            Webhost = webHost;
        }
        
                
        public IActionResult Index()
        {
            
           List<School> schools = new List<School>();
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand("sp_GetSchools", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataReader dr = cmd.ExecuteReader();
                    DataTable dt = new DataTable();
                    dt.Load(dr);
                    foreach(DataRow row in dt.Rows)
                    {
                        schools.Add(new School
                        {
                            SchoolsId = Convert.ToInt32(row["SchoolsId"]),
                            SchoolsName = row["SchoolsName"].ToString(),
                            Address = row["Address"].ToString(),
                            Phone = row["Phone"].ToString(),
                            Email = row["Email"].ToString(),
                            Logo = row["Logo"].ToString()
                           
                        });
                    }    

                }
            }
            return View(schools);
        }
        

        public IActionResult CreateSchool()
        {
            
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSchool(School school, IFormFile logo)
        {
            
            
            using (SqlConnection con = new SqlConnection(Configuration.GetConnectionString("DevConnection")))
            {
                con.Open();
                try
                {
                    using (SqlCommand cmd = new SqlCommand("sp_InsertSchools", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                      
                        cmd.Parameters.AddWithValue("@SchoolsName", school.SchoolsName);
                        cmd.Parameters.AddWithValue("@Address", school.Address);
                        cmd.Parameters.AddWithValue("@Phone", school.Phone);
                        cmd.Parameters.AddWithValue("@Email", school.Email);
                        string wwwRootPath = Webhost.WebRootPath;
                        if (logo != null && logo.Length > 0)
                        {
                            string fileName = Guid.NewGuid().ToString();
                            var uploads = Path.Combine(wwwRootPath, @"images\logo");
                            var extension = Path.GetExtension(logo.FileName);

                            using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                            {
                                logo.CopyTo(fileStreams);
                            }
                            school.Logo = @"images\logo" + fileName + extension;
                        }
                        cmd.Parameters.AddWithValue("@Logo", school.Logo);
                        cmd.ExecuteNonQuery();

                    }
                   

                }
                catch (Exception ex)
                {
                    ex.Message.ToString();
                }
             }
                return RedirectToAction("Index");
        }
        public IActionResult EditSchool(int? id)
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSchool(School school, int? id, IFormFile SchoolLogo)
        {
            return View();
        }
    }
}

Schools/Views/School/CreateSchool.cshtml
@model School
@{
    ViewData["Title"] = "CreateSchool";
}

<form method="post">
    <div class="border p-3 mt-4 row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create School
            </h2>
            <hr />
            <div class="mb-3 col-6">
                <label asp-for="SchoolsName">School Name</label>
                <input asp-for="SchoolsName" class="form-control" />
                <span asp-validation-for="SchoolsName" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Address">Address </label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Phone">Phone Number</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Email">Email Address</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Logo">Email Address</label>
                <input asp-for="Logo" class="form-control" type="file" name="logo" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="School" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    Back to School
                </a>
            </div>
           
        </div>
    </div>

</form>

Schools/Views/School/EditSchool.cshtml
@model School
@{
    ViewData["Title"] = "EditSchool";
}

<form method="post" enctype="multipart/form-data" asp-action="EditSchool">
    <div class="border p-3 mt-4 row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row pb-2">
            <h2 class="text-primary">
                Create School
            </h2>
            <hr />
            <div class="mb-3 col-6">
                <label asp-for="SchoolsName">School Name</label>
                <input asp-for="SchoolsName" class="form-control" />
                <span asp-validation-for="SchoolsName" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Address">Address </label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Phone">Phone Number</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="mb-3 col-6">
                <label asp-for="Email">Email Address</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
           
            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="School" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    Back to School
                </a>
            </div>

        </div>
    </div>

</form>

Schools/Views/School/Index.cshtml
@model IEnumerable<School>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">School</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="School" asp-action="CreateSchool" class="btn btn-primary" style="width:250px">
                Create New School
            </a>
        </div>
    </div>
</div>
<table class="table-bordered table-striped" style="width:100%">
    <thead>
        <tr>

            <th>School Name</th>
            <th>Address</th>
            <th>Phone </th>
            <th>Email </th>
            <th>Logo </th>
            <th><label>Action</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>

                <td width="120">
                    @obj.SchoolsName
                </td>
                <td width="170">
                    @obj.Address
                </td>
                <td width="20">
                    @obj.Phone
                </td>
                <td width="20">
                    @obj.Email
                </td>
                <td width="150">
                    @obj.Logo
                </td>
                <td width="100">
                    <a asp-controller="School" asp-action="EditAccountType" asp-route-id="@obj.SchoolsId" class="btn btn-success btn-mini"><i class="fas fa-edit"></i></a>
                    <a asp-controller="School" asp-action="DeleteAccountType" asp-route-id="@obj.SchoolsId" class="btn btn-danger btn-mini"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>